-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "transportCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportChargeGstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportChargeGstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PurchaseBill" ADD COLUMN     "transportCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportChargeGstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportChargeGstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
